# Welcome to Numpy Tutorial

In [2]:
import numpy as np 

In [3]:
myarr = np.array([3,6,32,7])

In [4]:
myarr

array([ 3,  6, 32,  7])

In [5]:
myarr.shape

(4,)

In [6]:
myarr.dtype

dtype('int64')

# Array creation: 1. Conversion from other Python structures (e.g., lists, tuples)

In [14]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [18]:
listarray.dtype

dtype('int64')

In [20]:
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [26]:
np.array({34,23,23})

array({34, 23}, dtype=object)

# 2. Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [31]:
zeros = np.zeros((2,5))

In [37]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
rng = np.arange(15)

In [43]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
lspace = np.linspace(1,5,4)

In [55]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [57]:
emp = np.empty((4,6))

In [59]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [63]:
emp_like = np.empty_like(lspace)

In [66]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [68]:
ide = np.identity(45)

In [70]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [72]:
ide.shape

(45, 45)

In [74]:
arr = np.arange(99)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [78]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [84]:
arr = arr.ravel()

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [86]:
arr.shape

(99,)

# Numpy Axis (y- axis0, x- axis1)

In [95]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [101]:
ar = np.array(x)

In [103]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
ar.sum(axis=0)

array([12,  8,  9])

In [107]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [111]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [113]:
ar.flat

In [115]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [117]:
ar.ndim

2

In [119]:
ar.size

9

In [121]:
ar.nbytes

72

In [123]:
one = np.array([1,3,4,634,2])

In [127]:
one.argmax()

3

In [129]:
one.argmin()

0

In [133]:
one.argsort()

array([0, 4, 1, 2, 3])

In [135]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [143]:
ar.argmax()

6

In [149]:
ar.argmax(axis=0)

array([2, 1, 1])

In [151]:
ar.argmax(axis=1)

array([2, 2, 0])

In [153]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [155]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [157]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [163]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [165]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [168]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [170]:
ar - ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [172]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [174]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [176]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [178]:
ar.sum()

29

In [180]:
ar.max()

7

In [182]:
ar.min()

0

# Finding Elements in an Array

In [185]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [189]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [193]:
type(np.where(ar>5))

tuple

In [195]:
np.count_nonzero(ar)

8

In [197]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [199]:
ar[1,2] = 0

In [201]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [203]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [205]:
import sys

In [211]:
py_ar = [0,4,55,2]

In [213]:
np_ar = np.array(py_ar)

In [217]:
np_ar

array([ 0,  4, 55,  2])

In [221]:
sys.getsizeof(1) * len(py_ar)

112

In [223]:
np_ar.itemsize * np_ar.size

32